config/routes.rb
Rails.application.routes.draw do
  
  root 'home#index' 

  scope(:path_names => { :new => "novo", :edit => "editar" }) do

    #location urls
    get "localizacao/cidades/estado/:state_id" => "location#cities_from_state"
    get "localizacao/estados" => "location#states"

    get "osid/novo" => "service_order_item_description#create" 
    get "osid/descricao" => "service_order_item_description#description_items", :as => "description_items"   

    resources :vehicles, :path => "veiculos", except: :destroy do
      collection do
        get "/:state_id/cities_from_state" => "vehicles#cities_from_state", :as => "cities_from_state", :format => :json
        get "/find" => "vehicles#find", :as => "find"
      end
    end

    resources :customers, :path => "clientes", except: :destroy do
      collection do
        get "/buscarVeiculos" => "customers#search_vehicle", :as => "search_vehicle"        
        get "/find" => "customers#find", :as => "find"
      end
    end

    resources :service_orders, :path => "os" do
      collection do
        get "/descricao" => "service_orders#description_items", :as => "description_items"
        get "/buscar" => "service_orders#find", :as => "buscar"
        get "/:id/emissao" => "service_orders#report", :as => "report"
        post "/enviar/email" => "service_orders#send_mail", :as => "send_mail"
      end
    end

    resources :users, :path => "usuarios", except: :destroy

    resource :company, :path => "empresa", :controller => :company, :only => [:edit, :show, :update, :create]

    devise_for :users, path: "", path_names: { sign_in: 'entrar', sign_out: 'sair', password: 'senha', confirmation: 'confirmacao', unlock: 'desbloqueio', registration: 'registro', sign_up: 'cadastro' }
  end

end

app/models/customer.rb
class Customer < ActiveRecord::Base
 # attr_accessible :id, :name, :address, :number, :neighborhood, :city, :cep, :cpf_cnpj, :email
  belongs_to :city
  belongs_to :user

  has_many :phones
  has_many :state_registrations
  has_many :customer_vehicle, dependent: :destroy
  has_many :customervehicle, through: :customer_vehicle, :source => :vehicle

  accepts_nested_attributes_for :customer_vehicle, allow_destroy: true
  accepts_nested_attributes_for :phones, allow_destroy: true
  accepts_nested_attributes_for :state_registrations, allow_destroy: true

  validates :user_id, presence: :true
  validates :name, presence: :true
  validates :cpf_cnpj, presence: :true

  before_save :treat_cpf_cnpj

  private
  		def treat_cpf_cnpj
  			self.cpf_cnpj = self.cpf_cnpj.gsub(/\D/,'').upcase
        self.cep = self.cep.gsub(/\D/,'').upcase
  		end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :set_customer, only: [:show, :edit, :update, :destroy]
  
  before_action :authenticate_user!
  
  layout "main_application"
  # GET /customers
  # GET /customers.json
  def index
    @customers = Customer.all.order("name").paginate(:page => params[:page], :per_page => 10)
  end

  def find

    order_by_param = "name"

    if (!params[:order_by_param].blank?)
      order_by_param = params[:order_by_param]
    end

    per_page_param = 10

    if (params[:per_page_param])
      per_page_param = params[:per_page_param]
    end

    @customers = Customer.where("name LIKE ? AND cpf_cnpj LIKE ?", "%#{params[:name]}%", "%"+"#{params[:cpf_cnpj]}%".gsub(/\D/,'')+"%").order(order_by_param).paginate(:page => params[:page], :per_page => per_page_param)

    respond_to do |format|
        format.html { render :index }
        format.json { 
          render json: {
            customers: @customers.as_json(:include => [:phones, :customervehicle]), 
            pagination: {
              total_pages: @customers.total_pages, 
              current_page: @customers.current_page, 
              total_entries: @customers.total_entries
            } 
          } 
        }
    end
  end

  # GET /customers/1
  # GET /customers/1.json
  def show
  end

  # GET /customers/new
  def new
    @customer = Customer.new
    @id_city = ""
    @id_state = ""
    @cities = City.none
    @vehicles = Vehicle.none
    @phones = Phone.none
  end

  # GET /customers/1/edit
  def edit

    if( @customer.city )
      @id_city = @customer.city.id
      @id_state = @customer.city.state.id
    end


    
    @vehicles = @customer.customer_vehicle

    @phones = @customer.phones
    

    load_cities_from_state()
  end

  # POST /customers
  # POST /customers.json
  def create
    @customer = Customer.new(customer_params)

    @customer.user = current_user

    respond_to do |format|
      if @customer.save
        format.html { redirect_to @customer, notice: 'Cliente criado com sucesso.' }
        format.json { render :show, status: :created, location: @customer }
      else
        format.html { render :new }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end

      @cities = []
      @vehicles = @customer.customer_vehicle

      @phones = @customer.phones
      if (@customer.city)
        @cities = load_cities(@customer.city.state_id)
      end

    end

   

  end

  # PATCH/PUT /customers/1
  # PATCH/PUT /customers/1.json
  def update
    respond_to do |format|

      @customer.user = current_user

      if @customer.update(customer_params)

        if(params[:removerVeiculos])
          vlr = params[:removerVeiculos].split(",");
          
          vlr.each do |item|  
            @customerVehicle = CustomerVehicle.find(item);
            @customerVehicle.destroy
          end
        end
        format.html { redirect_to @customer, notice: 'Cliente atualizado com sucesso.' }
        format.json { render :show, status: :ok, location: @customer }
      else
        format.html { render :edit }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end

      @cities = []
      @vehicles = @customer.customer_vehicle

      @phones = @customer.phones
      if (@customer.city)
        @cities = load_cities(@customer.city.state_id)
      end
    end

    
  end

  def cities_from_state
    @cities = City.joins(:state).where("states.id = ? ", params[:state_id])

    respond_to do |format|
      format.json { render json: @cities, :status => :created}
    end
  end
  
  def search_vehicle
     @vehicles = Vehicle.joins("LEFT JOIN customer_vehicles ON customer_vehicles.vehicle_id = vehicles.id")
     .where("vehicles.status = '1' AND (customer_id is null or customer_id <> ?) AND description LIKE ? AND license_plate LIKE ?","#{params[:customerid]}", "%#{params[:description]}%", "%#{params[:license_plate]}%".gsub("-","")).order("description").paginate(:page => params[:page], :per_page => 5)
     #,"#{params[:customerid]}"

    respond_to do |format|
      format.html {render partial: 'search_vehicle', locals: {:vehicles => @vehicles} }
      format.json {render json: @vehicles, :status => :created}
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_customer
      @customer = Customer.find(params[:id])
    end

    def load_cities(stateId)
      City.joins(:state).where("states.id = ? ", stateId)
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def customer_params
      params.require(:customer).permit(:id,:name,:address,:address2,:number,:neighborhood,:cep,:email,:city_id,:cpf_cnpj,:status,
                      :customer_vehicle_attributes => [:vehicle_id, :customer_id],:phones_attributes =>[:id,:number,:tp,:contact,:provider,:_destroy],
                      :state_registrations_attributes => [:id,:number,:description,:city_id,:_destroy])
    end

    def load_cities_from_state

      if(@customer.city)
        @cities = City.joins(:state).where("states.id = ? ", @customer.city.state.id)
      else
        @cities = City.none
      end

    end
end

app/helpers/customers_helper.rb
module CustomersHelper
	
	def format_phone_number(phone_number)
		phone_formatter =  phone_number

		if phone_number and phone_number.length == 10
			phone_formatter = phone_number.gsub(/\A(\d{2})(\d{4})(\d{4})\Z/, "\(\\1\)\\2-\\3")
		elsif phone_number and phone_number.length == 11			
			phone_formatter = phone_number.gsub(/\A(\d{2})(\d{5})(\d{4})\Z/, "\(\\1\)\\2-\\3")
		end
			
		phone_formatter 
	end

	def format_cpf_cnpj(cpf_cnpj)
		cpf_cnpj_formatter = cpf_cnpj

		if cpf_cnpj and cpf_cnpj.length == 11
			cpf_cnpj_formatter = cpf_cnpj.gsub(/\A(\d{3})(\d{3})(\d{3})(\d{2})\Z/, "\\1.\\2.\\3-\\4")
		elsif cpf_cnpj and cpf_cnpj.length == 14
			cpf_cnpj_formatter = cpf_cnpj.gsub(/\A(\d{2})(\d{3})(\d{3})(\d{4})(\d{2})\Z/, "\\1.\\2.\\3/\\4-\\5")
		end
			
		cpf_cnpj_formatter 
	end

	def format_cep(cep)
		cep_formatter = cep

		if cep and cep.length == 8
			cep_formatter = cep.gsub(/\A(\d{5})(\d{3})\Z/, "\\1-\\2")		
		end
		cep_formatter 
	end

	def load_cities(state)
		City.where("state_id = ?","#{state}")
	end

	def get_phones(customer)

		phones = ""

		if (not customer.nil? and customer.phones.length > 0)
			customer.phones.each do |p|
				phones += format_phone_number(p.number)
			end
		end

		phones
	end
end

app/views/customers/_form.html.erb
<%= form_for(@customer) do |f| %>
<!--<div class="row customer">-->
<ul id="tabs" class="nav nav-tabs" data-tabs="tabs">
  <li class="active"><a href="#dados" role="tab" class="btn btn-info" data-toggle="tab"><i class="fa fa-user"></i> Dados</a></li>
  <li class=""><a href="#veiculos" role="tab" class="btn btn-info" data-toggle="tab"><i class="fa fa-truck"></i> Veículos</a></li>
  <li class=""><a href="#phones" role="tab" class="btn btn-info" data-toggle="tab"><i class="fa fa-phone"></i> Telefones / <i class="fa fa-list-ul"></i> Insc. Estadual</a></li>

</ul>
<div >
  <div class="tab-content">
    <div class="tab-pane active" id="dados">
          <%= render :partial => 'pane_data', :locals => {:f => f} %>
    </div>
    <div class="tab-pane" id="veiculos">
          <%= render :partial => 'pane_vehicle', :locals => {:f => f} %>
    </div>
    <div class="tab-pane" id="phones">
      <%= render :partial => 'pane_phone', :locals => {:f => f} %>
    </div>
  </div>
  <div>
    <%= f.button :submit, class: "btn btn-primary", data: {disable_with: "<i class='fa fa-spinner fa-spin'></i> Salvando..."} do %>
      <i class="fa fa-save"></i> Salvar
    <% end %>

    <% if(@customer.id?) %>
       <%=  link_to @customer , :class => "btn btn-success" do %> 
        <i class="fa fa-eye"></i> Exibir
       <% end %>
    <% end %>

    <%= link_to customers_path, :class => "btn btn-default" do %>
        <i class="fa fa-list-ul"></i> Listar Clientes
    <% end %>
  </div>
  
</div>
<!--</div>-->
<%= render 'layouts/loading_modal' %>

<div id="remover_veiculo_modal" class="modal bs-example-modal-sm" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-sm">
      <div class="modal-content">
        <div class="modal-header">
           <!-- <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>-->
            <h4 class="modal-title" id="myModalLabel"><i class="fa fa-trash-o"></i> Remover</h4>
          </div>
          <div class="modal-body">
            Remover Veículo ?
          </div>  
           <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal" onclick="$('.table-data-add-veiculos tr.danger').removeClass('danger')">Fechar</button>
            <button type="button" class="btn btn-danger" onclick="Customer.removerVeiculoPopup();">Remover</button>
          </div>      
      </div>
  </div>
</div>


<div id="remover_phone_modal" class="modal bs-example-modal-sm" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-sm">
      <div class="modal-content">
        <div class="modal-header">
            <h4 class="modal-title" id="myModalLabel"><i class="fa fa-trash-o"></i> Remover</h4>
          </div>
          <div class="modal-body">
            Remover Telefone ?
          </div>  
           <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal" onclick="$('.table-phones tr.danger').removeClass('danger')">Fechar</button>
            <button type="button" class="btn btn-danger" onclick="Customer.removePhonePopup();">Remover</button>
          </div>      
      </div>
  </div>
</div>

<div id="remover_sr_modal" class="modal bs-example-modal-sm" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-sm">
      <div class="modal-content">
        <div class="modal-header">
            <h4 class="modal-title" id="myModalLabel"><i class="fa fa-trash-o"></i> Remover</h4>
          </div>
          <div class="modal-body">
            Remover Inscrição Estadual ?
          </div>  
           <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal" onclick="$('.table-state-registrations tr.danger').removeClass('danger')">Fechar</button>
            <button type="button" class="btn btn-danger" onclick="Customer.removeSRPopup();">Remover</button>
          </div>      
      </div>
  </div>
</div>

<style type="text/css">
  .nav > li > a:hover, .nav > li > a:focus{
    background-color: #2aabd2;
  }
  .has-feedback .form-control-feedback{
    width: 54px;
  }
</style>
<script type="text/javascript">
    jQuery(document).ready(function ($) {        
        Customer.init();
        $("#license_plate").inputmask("aaa-9999");                
        Common.buttonStatus("#customer_status")
    });
</script> 
<% end %>

app/views/customers/_pane_vehicle.html.erb
	<div class="row">
		 <div class="form-group col-lg-6">
	            <div class="panel panel-info">
			    <div class="panel-heading">
			        <h3 class="panel-title"><i class="fa fa-search"></i> Buscar</h3>
			    </div>
			    <div class="panel-body">
			        <%= form_tag search_vehicle_customers_path , :method => "get" do%>
			          <div class="row">
			            <div class="form-group-sm col-lg-4">
			              <%= label_tag(:description, "Descrição") %>
			              <%= text_field_tag(:description, params[:description], class: "form-control") %>
			            </div>
			            <div class="form-group-sm col-lg-4">
			              <%= label_tag(:license_plate, "Placa") %>
			              <%= text_field_tag(:license_plate, params[:license_plate], class: "form-control") %>
			            </div>			           
			          </div>
			          <%= hidden_field_tag(:customerid, @customer.id)%>
			           <div class="row" style="margin-top: 23px;">
			           		<div class="form-group-sm col-lg-4">
				              <%= button_tag id: "buscarVeiculos", class: "btn btn-primary", type: "button" do %>
				                <i class="fa fa-search"></i> Buscar
				              <% end %>              
			              </div>
			            </div>
			        <% end %>
			        <br/>
			        <div id="tabela"></div>
			    </div>
			</div>
	     </div>
	      <div class="form-group col-lg-6">
	            <div class="panel panel-success">
			    <div class="panel-heading">
			        <h3 class="panel-title"><i class="fa fa-truck"></i> Veículos do Cliente</h3>
			    </div>
			    <div class="panel-body">
				    <%# f.fields_for :customer_vehicle, @customer.customer_vehicle.build do |v| %>
				    
				    <%# v.text_field :vehicle_id %>
				    <%#v.text_field :customer_id %>
				    <%#end%>
			        <table class="table table-bordered table-hover table-data table-data-add-veiculos">
					    <thead>
					      <tr>
					        <th>Descrição</th>
					        <th>Placa</th>
					        <th style="width:40px">Remover</th>
					      </tr>
					    </thead>
					    <tbody>					    	
						    <% @vehicles.each_with_index do |vh,idx| %>
						    	<tr data-id="<%=vh.id%>">
						    		<td><%=vh.vehicle.description %></td>
						    		<td><%= format_license_plate(vh.vehicle.license_plate) %></td>
						    		<td >
						    			 <%= button_tag id: "removerVeiculo", class: "removerVeiculo btn btn-danger btn-xs center-block", type: "button" do %>
							                <i class="fa fa-trash-o"></i>
							              <% end %>  
						    		</td>
						    	</tr>
							<%end%>
						</tbody>
					</table>	
					<input type="hidden" id="removerVeiculos" name="removerVeiculos" value=""/>				
			    </div>
			</div>
	     </div>
	</div>

app/views/customers/_search_vehicle.html.erb
<table class="table table-bordered table-hover table-data">
    <thead>
      <tr>
        <th>Descrição</th>
        <th>Placa</th>        
        <th style="width:40px">Ação</th>
      </tr>
    </thead>
    <tbody class="table-data-search">
	    <% @vehicles.each do |vh| %>
	    	<tr >
	    		<td><%=vh.description%></td>
	    		<td><%=format_license_plate(vh.license_plate)%></td>	    		
          <td style="text-align:center" data-id="<%=vh.id%>">
             <%= button_tag id: "addVeiculos", class: "addVeiculos btn btn-success btn-xs", type: "button" do %>
                <i class="fa fa-plus"></i>
            <% end %> 
          </td>
	    	</tr>
		<%end%>
	</tbody>
</table>
<div class="row-fluid" align="center">
  <% will_paginate @vehicles , next_label: "»",previous_label: "«", renderer: BootstrapPagination::Rails%>
</div>

app/views/customers/edit.html.erb
<h1>Editar Cliente</h1>

<br class="visible-xs-* visible-md-*" />

<ol class="breadcrumb">
  <li class="active"><i class="fa fa-home"></i> <%= link_to 'Home', root_path %></li>
  <li class="active"><i class="fa fa-list-ul"></i> <%= link_to 'Lista de Clientes', customers_path %></li>
      <li class="active"><i class="fa fa-user"></i> Cliente</li>
</ol>
<hr/>
<%= render 'form' %>

app/views/customers/index.html.erb
<h1>Lista de Clientes</h1>

<br class="visible-xs-* visible-md-*" />

<ol class="breadcrumb">
  <li ><i class="fa fa-home"></i> <%= link_to 'Home', root_path %></li>
  <li class="active"><i class="fa fa-users"></i> Clientes</li>
</ol>
<hr/>
<div class="panel panel-primary">
    <div class="panel-heading">
        <h3 class="panel-title"><i class="fa fa-search"></i> Buscar</h3>
    </div>
    <div class="panel-body">
        <%= form_tag find_customers_path , :method => "get" do%>
          <div class="row">
            <div class="form-group-sm col-lg-2">
              <%= label_tag(:name, "Nome") %>
              <%= text_field_tag(:name, params[:name], class: "form-control") %>
            </div>
            <div class="form-group-sm col-lg-2">
              <%= label_tag(:cpf_cnpj, "CPF/CNPJ") %>
              <%= text_field_tag(:cpf_cnpj, params[:cpf_cnpj], class: "form-control") %>
            </div>
            <div class="form-group-sm col-lg-2" style="margin-top: 23px;">
              <%= button_tag :submit, class: "btn btn-primary" do %>
                <i class="fa fa-search"></i> Buscar
              <% end %>              
            </div>
          </div>
        <% end %>
    </div>
</div>
<%= link_to new_customer_path , :class => "btn btn-primary" do %>
  <i class="fa fa-user"> Novo</i>
<% end %>
<br/><br/>
<!--<div class="table-responsive">-->
  <table class="table table-bordered table-hover table-data">
   <thead>
      <tr>
        <th>Nome</th>
        <th class="hidden-sm hidden-xs">CPF/CNPJ</th>
        <th class="hidden-sm hidden-xs">Endereço</th>
        <th class="hidden-sm hidden-xs">Cidade</th>
        <th class="hidden-sm hidden-xs">CEP</th>
        <th class="hidden-sm hidden-xs">E-Mail</th>
        <% if (policy(Customer).show_user_column?) %>
          <th class="hidden-sm hidden-xs">Alterado por</th>
        <% end %>
        <th style="width:98px" class="last"></th>
      </tr>
    </thead>

  <tbody>
    <% @customers.each do |customer| %>
      <tr>
        <td class="<%= customer.status == '1' ? 'status-ativo' : 'status-inativo'%>"><%= customer.name %></td>
        <td class="hidden-sm hidden-xs"><%= format_cpf_cnpj(customer.cpf_cnpj) %></td>
        <td class="hidden-sm hidden-xs"><%= customer.address + (customer.number.empty? ? '' : ', '+customer.number) %></td>
        <td class="hidden-sm hidden-xs"><%= customer.city ? customer.city.name + ' - ' + customer.city.state.uf : '' %></td>
        <td class="hidden-sm hidden-xs"><%= format_cep(customer.cep) %></td>
        <td class="hidden-sm hidden-xs"><%= customer.email %></td>
        <% if (policy(Customer).show_user_column?) %>
          <td class="hidden-sm hidden-xs"><%= customer.user.nil? ? "" : customer.user.full_name %></td>
        <% end %>
        <td class="last">
          <div class="btn-group dropup btn-group-table">
              <button type="button" class="btn btn-success" data-toggle="dropdown">Ações</button>
              <button type="button" class="btn btn-success dropdown-toggle" data-toggle="dropdown">
                <span class="caret"></span>
                <span class="sr-only">Toggle Dropdown</span>
              </button>
              <ul class="dropdown-menu" role="menu">
                 <li><%= link_to customer do %><i class="fa fa-eye"> Exibir</i><% end %></li>
                 <li><%= link_to edit_customer_path(customer) do%><i class="fa fa-edit"> Editar</i><% end %></li>
              </ul>
            </div>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<div class="row-fluid" align="center">
  <%= will_paginate @customers,next_label: "»",previous_label: "«", renderer: BootstrapPagination::Rails%>
</div>
<br>
<!--</div>-->
<%= link_to new_customer_path , :class => "btn btn-primary" do %>
  <i class="fa fa-user"> Novo</i>
<% end %>
<script type="text/javascript">
    jQuery(document).ready(function ($) {  
      $("#cpf_cnpj").on("keyup", function(){
          valor = $(this).val().replace( /\D/g , "");
          if(valor.length <= 11)
            $(this).inputmask({mask:"999.999.999-99[9]"});
          else if(valor.length > 11)
            $(this).inputmask("99.999.999/9999-99");
      });
    });
</script>

app/views/customers/new.html.erb
<div class="row">
  <div class="col-lg-12">
	<h1>Novo Cliente</h1>
  <br class="visible-xs-* visible-md-*" />
	<ol class="breadcrumb">
      <li class="active"><i class="fa fa-home"></i> <%= link_to 'Home', root_path %></li>
      <li class="active"><i class="fa fa-list-ul"></i> <%= link_to 'Lista de Clientes', customers_path %></li>
      <li class="active"><i class="fa fa-user"></i> Cliente</li>
    </ol>
    <hr/>    
	<%= render 'form' %>

  </div>
</div>

app/views/customers/show.html.erb
<h1>Cliente <strong><%= @customer.name %></strong></h1>
<br class="visible-xs-* visible-md-*" />
<ol class="breadcrumb">
  <li class="active"><i class="fa fa-home"></i> <%= link_to 'Home', root_path %></li>
  <li class="active"><i class="fa fa-list-ul"></i> <%= link_to 'Lista de Veículos', customers_path %></li>
  <li class="active"><i class="fa fa-user"></i> Cliente</li>
</ol>
<hr/>
<div class="row">
  <% if (notice) %>
	<div class="alert alert-info alert-dismissable">
		<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
		<i class="fa fa-truck"></i> <%= notice %>
	</div>
  <% end %>
  
  <div class="col-lg-4">
    <div class="form-group">
        <div class="panel panel-info">
          <div class="panel-heading">
              <h3 class="panel-title"><i class="fa fa-user"></i> Dados</h3>
          </div>
          <div class="panel-body">
            <div class="form-group">
              <label class="col-lg-4-sm control-label">CPF/CNPJ:</label>
              <span class="form-control-static"><%= format_cpf_cnpj(@customer.cpf_cnpj) %></span>
            </div>
            <div class="form-group">
              <label class="col-lg-4-sm control-label">Nome:</label>
                <span class="form-control-static"><%= @customer.name %></span>
            </div>
            <div class="form-group">
              <label class="col-lg-4-sm control-label">Endereço:</label>
                <span class="form-control-static"><%= @customer.address + (@customer.number.empty? ? '' : ', '+@customer.number) %></span>
            </div>
            <div class="form-group">
              <label class="col-lg-4-smcontrol-label">Bairro:</label>
                <span class="form-control-static"><%= @customer.neighborhood%></span>
            </div>
            <div class="form-group">
              <label class="col-lg-4-sm control-label">CEP:</label>
                <span class="form-control-static"><%= format_cep(@customer.cep)%></span>
            </div>
             <div class="form-group">
              <label class="col-lg-4-sm control-label">Cidade:</label>
                <span class="form-control-static"><%= @customer.city ? @customer.city.name : '' %></span>
            </div>
             <div class="form-group">
              <label class="col-lg-4-sm control-label">Estado:</label>
                <span class="form-control-static"><%= @customer.city ? @customer.city.state.name : '' %></span>
            </div>
            <div class="form-group">
              <label class="col-lg-4-sm control-label">E-mail:</label>
                <span class="form-control-static"><%= @customer.email%></span>
            </div> 
             <div class="form-group">
              <label class="col-lg-4-sm control-label">Status:</label>
              <span class="label label-<%=@customer.status == '1' ? 'success' : 'danger' %>"><%= format_status(@customer.status)%></span>
            </div> 
          </div>
        </div>
      </div>
      <div class="form-group">
        <div class="panel panel-success col-lg-4-sm">
          <div class="panel-heading">
              <h3 class="panel-title"><i class="fa fa-truck"></i> Veículos</h3>
          </div>
          <div class="panel-body">
              <table class="table table-bordered table-hover table-data table-data-add-veiculos">
                <thead>
                  <tr>
                    <th>Descrição</th>
                    <th>Placa</th>
                  </tr>
                </thead>
                <tbody>               
                  <% @customer.customer_vehicle.each_with_index do |vh,idx| %>
                    <tr>
                      <td><%=vh.vehicle.description %></td>
                      <td><%= format_license_plate(vh.vehicle.license_plate) %></td>
                    </tr>
                <%end%>
              </tbody>
            </table>  
          </div>     
        </div>
      </div> 
    </div>

    <div class="col-lg-6">  

      <div class="form-group">
        <div class="panel panel-warning">
          <div class="panel-heading">
              <h3 class="panel-title"><i class="fa fa-phone"></i> Telefones</h3>
          </div>
          <div class="panel-body">
                <table class="table table-bordered table-hover table-data table-phones">
                <thead>
                  <tr>
                    <th style="width:150px">Número</th>
                    <th>Tipo</th>
                    <th>Contato</th>
                    <th>Operadora</th>
                  </tr>
                </thead>
                <tbody>
                  <% @customer.phones.each_with_index do |p| %>
                    <tr>
                      <td><%=format_phone_number(p.number)%></td>
                      <td><%=p.tp %> </td>
                      <td><%=p.contact%></td>
                      <td><%=p.provider %></td>
                    </tr>
                  <%end%>
              </tbody>
            </table>  
          </div>
        </div>
      </div>       
      <div class="form-group">
        <div class="panel panel-danger col-lg-4-sm">
            <div class="panel-heading">
                <h3 class="panel-title"><i class="fa fa-list-ul"></i> Inscrição Estadual</h3>
            </div>
            <div class="panel-body">
                <table class="table table-bordered table-hover table-data table-state-registrations">
                  <thead>
                    <tr>
                      <th style="width:150px">Número</th> 
                      <th>Descrição</th> 
                      <th>Cidade/Estado</th> 
                    </tr>
                  </thead>
                  <tbody>               
                    <% @customer.state_registrations.each_with_index do |sr,idx| %>
                      <tr>
                        <td><%=sr.number %></td>
                        <td><%=sr.description %></td>
                        <td><%= (sr.city) ? (sr.city.name + " - " + sr.city.state.uf) : ''%></td>
                      </tr>
                  <%end%>
                </tbody>
              </table>  
          </div>
        </div>
      </div>
  </div>  
</div>
<hr/>
<%= link_to new_customer_path , :class => "btn btn-primary" do %>
  <i class="fa fa-user"> Novo</i>
<% end %>

<%= link_to  edit_customer_path(@customer), :class => "btn btn-info" do %>
	<i class="fa fa-edit"></i> Editar
<% end %>

<%= link_to customers_path, :class => "btn btn-default"  do %>
	<i class="fa fa-list-ul"></i> Listar Cliente
<% end %>