config/routes.rb
Rails.application.routes.draw do
  
  root 'home#index' 

  scope(:path_names => { :new => "novo", :edit => "editar" }) do

    #location urls
    get "localizacao/cidades/estado/:state_id" => "location#cities_from_state"
    get "localizacao/estados" => "location#states"

    get "osid/novo" => "service_order_item_description#create" 
    get "osid/descricao" => "service_order_item_description#description_items", :as => "description_items"   

    resources :vehicles, :path => "veiculos", except: :destroy do
      collection do
        get "/:state_id/cities_from_state" => "vehicles#cities_from_state", :as => "cities_from_state", :format => :json
        get "/find" => "vehicles#find", :as => "find"
      end
    end

    resources :customers, :path => "clientes", except: :destroy do
      collection do
        get "/buscarVeiculos" => "customers#search_vehicle", :as => "search_vehicle"        
        get "/find" => "customers#find", :as => "find"
      end
    end

    resources :service_orders, :path => "os" do
      collection do
        get "/descricao" => "service_orders#description_items", :as => "description_items"
        get "/buscar" => "service_orders#find", :as => "buscar"
        get "/:id/emissao" => "service_orders#report", :as => "report"
        post "/enviar/email" => "service_orders#send_mail", :as => "send_mail"
      end
    end

    resources :users, :path => "usuarios", except: :destroy

    resource :company, :path => "empresa", :controller => :company, :only => [:edit, :show, :update, :create]

    devise_for :users, path: "", path_names: { sign_in: 'entrar', sign_out: 'sair', password: 'senha', confirmation: 'confirmacao', unlock: 'desbloqueio', registration: 'registro', sign_up: 'cadastro' }
  end

end

app/models/service_order.rb
class ServiceOrder < ActiveRecord::Base
  belongs_to :vehicle
  belongs_to :user
  belongs_to :customer, :foreign_key => 'customer_id'

  validates :customer_id, presence: :true  
  validates :observations, length: { in: 0..4000 }
  validates :payment_date, presence: :true, :if => :is_payment_type_set?
  validates :discount, presence: :true, :if => :is_valid_discount?

  has_many :service_order_item, :dependent => :destroy
  accepts_nested_attributes_for :service_order_item, :allow_destroy => true

  def is_payment_type_set?
    if(payment_type != 7 and payment_type != 9)
      return true
    end
    return false
  end

  def is_valid_discount?
    if(discount.nil?)
      return 0
    end
    return discount
  end

  scope :search_os, ->(params){
  	
  	where_clause = String.new

    if(params)
      if(!params[:id_os].blank?)
        where_clause = " service_orders.id = " << params[:id_os] << " AND"
      end
    	if(!params[:customer_id].blank?)
    		where_clause = " service_orders.customer_id = " << params[:customer_id] << " AND"
    	end
    	if(!params[:vehicle].blank? and !params[:vehicle].gsub("Selecione...","").blank?)
    		where_clause += " service_orders.vehicle_id = " << params[:vehicle] << " AND"
    	end

    	#ifs de payment date
    	if(!params[:payment_date_de].blank? and !params[:payment_date_ate].blank? )
    		where_clause += " service_orders.payment_date between '" << Date.strptime(params[:payment_date_de],"%d/%m/%Y").to_s() << "' and '" << Date.strptime(params[:payment_date_ate],"%d/%m/%Y").to_s() << "' AND"
    	end

    	#se somente preenchido payment date de
    	if(!params[:payment_date_de].blank? and params[:payment_date_ate].blank? )
    		where_clause += " service_orders.payment_date <= '" << Date.strptime(params[:payment_date_de],"%d/%m/%Y").to_s() << "' AND"
    	end

    	#se somente preenchido payment date ate
    	if(params[:payment_date_de].blank? and !params[:payment_date_ate].blank? )
    		where_clause += " service_orders.payment_date >= '" << Date.strptime(params[:payment_date_ate],"%d/%m/%Y").to_s() << "' AND"
    	end

    	#ifs de created_at
    	if(!params[:created_date_de].blank? and !params[:created_date_ate].blank? )
    		where_clause += " service_orders.created_at between '" << Date.strptime(params[:created_date_de],"%d/%m/%Y").to_s() << "' and '" << Date.strptime(params[:created_date_ate],"%d/%m/%Y").to_s() << "' AND"
    	end

    	#se somente preenchido created_at de
    	if(!params[:created_date_de].blank? and params[:created_date_ate].blank? )
    		where_clause += " service_orders.created_at <= '" << Date.strptime(params[:created_date_de],"%d/%m/%Y").to_s() << "' AND"
    	end

    	#se somente preenchido created_at ate
    	if(params[:created_date_de].blank? and !params[:created_date_ate].blank? )
    		where_clause += " service_orders.created_at >= '" << Date.strptime(params[:created_date_ate],"%d/%m/%Y").to_s() << "' AND"
    	end 

    	#se os foi criada
    	if(!params[:os_created].blank?)
    		where_clause += " service_orders.os_created = " << (params[:os_created] == "false" ? '0' : '1') << " AND"
    	end

    	#os pagas
    	if(!params[:paid].blank?)
    		#where_clause += " service_orders.payment_date " << (params[:paid] == "false" ? 'IS NULL' : ' IS NOT NULL') << " AND"
        where_clause += " service_orders.paid =" << (params[:paid] == "false" ? '0' : '1') << " AND"
    	end

    	#os pagas
    	if(!params[:help].blank?)
    		where_clause += " service_orders.help = " << (params[:help] == "false" ? '0' : '1') << " AND"    		
    	end
    end
    #expressão para remover ultimo AND ou AND)
    where(where_clause.gsub(/((AND\))$|(AND))$/,""))
  }

  scope :by_vehicle, lambda { |vehicle|
    return scoped unless (vehicle.present?) 
    where(:vehicle_id => vehicle)
  }

  scope :paid, lambda { |paid|

    if(paid[:paid].nil? or paid[:paid].blank?)
      return where("")
    else
      return where(:paid => paid[:paid].to_s == "true" ? true : false )    
    end    
  }

  scope :months_total, ->(data_de, data_ate){
    where( " DATE_FORMAT(payment_date,'%Y-%m') between '#{data_de}' and '#{data_ate}' " )
  }
end

app/controllers/service_orders_controller.rb
# encoding: utf-8

class ServiceOrdersController < ApplicationController

  before_action :set_service_order, only: [:show, :edit, :update, :destroy, :report]

  before_action :authenticate_user!

  # after_action :verify_authorized

  layout "main_application"
  
  # GET /service_orders
  # GET /service_orders.json
  def index
    @customer = Customer.new

    per_page_param = 10

    if (params[:per_page_param])
      per_page_param = params[:per_page_param]
    end

    @service_orders = ServiceOrder.select("service_orders.id,service_orders.created_at,customer_id,vehicle_id,payment_date,os_created,order_date,help,payment_type,sum(service_order_items.unit_price) as subtotal,sum(service_order_items.unit_price) - service_orders.discount as total,service_orders.discount as discount,service_orders.paid,user_id")
    .joins(:service_order_item).group("service_order_items.service_order_id").order("service_orders.created_at DESC")
    .order("service_orders.created_at DESC")
    .paginate(:page => params[:page], :per_page => per_page_param)


  end

  # GET /service_orders/1
  # GET /service_orders/1.json
  def show

    @company = Company.first

    respond_to do |format|
      format.html

      format.pdf do 
        render :pdf  => "ordem_servico_" + @service_order.id.to_s
      end
    end

  end

  # GET /service_orders/new
  def new
    @service_order = ServiceOrder.new
    @service_order.os_created = false
    @service_order.help = false
    @service_order.service_order_item.build
    @vehicles = []
  end

  # GET /service_orders/1/edit
  def edit
    vehicle_of_customer
  end

  # POST /service_orders
  # POST /service_orders.json
  def create
    @service_order = ServiceOrder.new(service_order_params)

    @service_order.user = current_user

    respond_to do |format|
      if @service_order.save
        format.html { redirect_to @service_order, notice: 'Ordem de Serviço criada com sucesso' }
        format.json { render :show, status: :created, location: @service_order }
      else
        vehicle_of_customer
        format.html { render :new }
        format.json { render json: @service_order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /service_orders/1
  # PATCH/PUT /service_orders/1.json
  def update

    @service_order.user = current_user
    
    respond_to do |format|
      if @service_order.update(service_order_params)
        format.html { redirect_to @service_order, notice: 'Ordem de serviço atualizada com sucesso' }
        format.json { render :show, status: :ok, location: @service_order }
      else
        vehicle_of_customer
        format.html { render :edit }
        format.json { render json: @service_order.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy

    ServiceOrder.find(params[:id]).destroy;

    if(!params[:customer_id].blank?)
      @customer = Customer.find(params[:customer_id])      
    end


    per_page_param = 10

    if (params[:per_page_param])
      per_page_param = params[:per_page_param]
    end

     @service_orders = ServiceOrder.select("service_orders.id,service_orders.created_at,customer_id,vehicle_id,payment_date,os_created,order_date,help,payment_type,,sum(service_order_items.unit_price) as subtotal,sum(service_order_items.unit_price)  - service_orders.discount as total,service_orders.discount as discount,service_orders.paid,user_id")
    .joins(:service_order_item)
    .search_os(params)
    .group("service_order_items.service_order_id").order("service_orders.created_at DESC")
    .paginate(:page => params[:page], :per_page => per_page_param)

    respond_to do |format|
        format.html { redirect_to service_orders_path, notice: 'Ordem de serviço excluida com sucesso' }
    end
  end

  def find
    
    @customer = Customer.new

    if(!params[:customer_id].blank?)
      @customer = Customer.find(params[:customer_id])      
    end

    per_page_param = 10

    if (params[:per_page_param])
      per_page_param = params[:per_page_param]
    end

     @service_orders = ServiceOrder.select("service_orders.id,service_orders.created_at,customer_id,vehicle_id,payment_date,os_created,order_date,help,payment_type,sum(service_order_items.unit_price) as subtotal,sum(service_order_items.unit_price)  - service_orders.discount as total,service_orders.discount as discount,service_orders.paid,user_id")
    .joins(:service_order_item)
    .search_os(params)
    .group("service_order_items.service_order_id").order("service_orders.created_at DESC")
    .paginate(:page => params[:page], :per_page => per_page_param)

    respond_to do |format|        
        format.html { render :index }
    end

  end

  #def description_items
  #  estados = [id:params["q"], name: params["q"]]
  #  respond_to do |format|       
  #     format.json { render json: estados, status: :created }
  #  end
  #end

  def description_items
    estados = [id:params["q"], name: params["q"]]
    debug(params)
    respond_to do |format|       
       format.json { render json: estados, status: :created }
    end
  end

  def report
    @company = Company.first
    render layout: "report_application"
  end

  # POST
  def send_mail

    @service_order = ServiceOrder.find(params[:so_id])
    @company = Company.first

    nf_file = nil
    
    if (params[:nf_file])
      nf_file = params[:nf_file].read
    end

    so_file = WickedPdf.new.pdf_from_string(render_to_string('service_orders/show.pdf.erb'))

    ApplicationMailer.send_so(@service_order, so_file, nf_file).deliver()

    email_log = EmailLog.new
    email_log.email_from = "mecanicabalsamobenz@hotmail.com"
    email_log.service_order = @service_order

    respond_to do |format|
      if email_log.save
        format.html { redirect_to service_orders_path, notice: "Ordem de Serviço número #{params[:so_id]} enviada por email"  }
      else
        format.html { redirect_to service_orders_path, alert: "Erro ao enviar Ordem de Serviço número #{params[:so_id]} por email" }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_service_order
      @service_order = ServiceOrder.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def service_order_params
      params.require(:service_order).permit(:customer_id, :vehicle_id, :payment_date, :os_created, :order_date, :payment_type, :help,:paid,:observations,:km_service,:discount,:_destroy, 
          :service_order_item_attributes => [:id,:soi_date, :service_order_item_description_id,:unit_price,:_destroy])
    end

    def vehicle_of_customer 
      @vehicles =  Vehicle.joins("INNER JOIN customer_vehicles ON customer_vehicles.vehicle_id = vehicles.id")
      .where("vehicles.status = '1' AND (customer_id = ?)",@service_order.customer_id)

      vehicle = Vehicle.new
      vehicle.id = ""
      vehicle.license_plate = ""
      vehicle.description="Selecione...."
      @vehicles.append(vehicle)
    end
end

app/helpers/service_orders_helper.rb
module ServiceOrdersHelper

	def format_status_os_busca_class(status)
		if(status.blank?)
			return "btn-info";
		end
		
		if(status == "true")
			"btn-success"
		else
			"btn-danger"
		end
	end

	def format_status_os_busca(status)
		if(status.blank?)
			return "Todos";
		end

		if(status == "true")
			"Sim"
		else
			"Não"
		end
	end

	def format_status_os(status)
		if(status)
			"Sim"
		else
			"Não"
		end
	end

	def format_status_os_class(status)
		if(status)
			"btn-success"
		else
			"btn-danger"
		end
	end

	def tipo_pagamento_desc(tp_pagamento_code)
		desc = ""
		case tp_pagamento_code
		when 1
			desc = "À Vista"
		when 2
			desc = "Cheque"
		when 3
			desc = "Cartão"
		when 4
			desc = "30 Dias"
		when 5
			desc = "60 Dias"
		when 6
			desc = "90 Dias"
		when 7
			desc = "Não Pago"
		when 8
			desc = "Boleto"
		when 9
			desc = "Orçamento"
		else
			desc="Não Informada"
		end
	end
end

app/views/service_orders/_pago_msg_error.html.erb
<div id="pagoMSGError" class="modal bs-example-modal-sm" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel" aria-hidden="true">
	<div class="modal-dialog modal-sm">
	    <div class="modal-content">
		    <div class="modal-header" style="color:red">
		        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
		        <h4 class="modal-title" id="myModalLabel"><i class="fa fa-exclamation-circle"></i> Erro</h4>
	      	</div>
	      	<div class="modal-body">
	        	<h5><strong style="color:red;">Tipo de pagamento, não pode ser igual a Orçamento ou Não Pago, favor alterar!</strong></h5>
	      	</div>	
	      	 <div class="modal-footer">
	            <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
          </div>       
	    </div>
  </div>
</div>

app/views/service_orders/_send_mail.html.erb
<div id="sendMailDialog" class="modal bs-example-modal-md" tabindex="-1" role="dialog" aria-labelledby="sendMailModalLabel" aria-hidden="true">
	<div class="modal-dialog modal-md">
	    <div class="modal-content">
	    	<%= form_tag(send_mail_service_orders_path, multipart: true) do %>
			    <div class="modal-header">
			        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
			        <h4 class="modal-title" id="sendMailModalLabel"><i class="fa fa-mail-forward"></i> Enviar Email</h4>
		      	</div>
		      	<div class="modal-body">
		        	<p>
		        		Envio de Ordem de Serviço. Deseja enviar nota fiscal? Faça o upload do arquivo.
		        	</p>
		        	<hr/>
		        	
		        		<%= hidden_field_tag :so_id%>
		        		<label for="nf_file">Nota Fiscal</label>
	    				<%= file_field_tag :nf_file %>
		        	
		      	</div>	
		      	 <div class="modal-footer">
		            <button type="button" class="btn btn-default" data-dismiss="modal">
		            	<i class="fa fa-times"></i> Cancelar
		            </button>
		            <%= button_tag :class => "btn btn-primary", data: {disable_with: "<i class='fa fa-spinner fa-spin'></i> Enviando email..."} do %>
		            	<i class="fa fa-mail-forward"></i> Enviar
		           	<% end %>
	          	</div>
          	<% end %>
	    </div>
  </div>
</div>
<script type="text/javascript">
	ServiceOrder.initMailingAction();
</script>

app/views/service_orders/edit.html.erb
<h1>Editar Ordem de Serviço</h1>
<ol class="breadcrumb">
  <li class="active"><i class="fa fa-home"></i> <%= link_to 'Home', root_path %></li>
  <li class="active"><i class="fa fa-list-ul"></i> <%= link_to 'Lista Ordem de Serviços', service_orders_path %></li>
      <li class="active"><i class="fa fa-file-text"></i> Cliente</li>
</ol>
<hr/>
<%= render 'form' %>

app/views/service_orders/index.html.erb
<h1>Ordem de Serviços</h1>
<ol class="breadcrumb">
  <li ><i class="fa fa-home"></i> <%= link_to 'Home', root_path %></li>
  <li class="active"><i class="fa fa-file-text"></i> Ordem de Serviços</li>
</ol>
<hr/>
<% if (notice) %>
  <div class="alert alert-info alert-dismissable">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
    <i class="fa fa-company"></i> <%= notice %>
  </div>
  <br/>
<% elsif (alert) %>
  <div class="alert alert-danger alert-dismissable">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
    <i class="fa fa-company"></i> <%= alert %>
  </div>
  <br/>
<% end %>
<div class="panel panel-primary">
    <div class="panel-heading">
        <h3 class="panel-title"><i class="fa fa-search"></i> Buscar</h3>
    </div>
    <div class="panel-body">
        <%= render 'search_os'%>
    </div>

    <table class="table table-bordered table-hover table-data tblso">
    <thead>
      <tr>
        <th title="Número da Ordem de Serviço">N°</th>
        <th >Cliente</th>
        <th class="hidden-sm hidden-xs">Veículo</th>
        <th class="hidden-sm hidden-xs" title="Data Criação">Dt. Criação</th>
        <th class="hidden-sm hidden-xs" title="Data Pagamento">Dt. Pgto</th>
        <th class="hidden-sm" style="padding: 8px 2px; width:6px">Pago</th>
        <th class="hidden-sm hidden-xs" style="padding: 8px 2px; width:6px" title="Ordem de Serviço">OS</th>
        <th class="hidden-sm hidden-xs" style="padding: 8px 2px; width:6px" title="Socorro">Soc.</th>
        <th class="hidden-sm hidden-xs" title="Tipo Pagamento">Tpo Pgto.</th>
        <% if (policy(ServiceOrder).show_user_column?) %>
          <th  style="width:80px">Alterado</th>
        <% end %>
        <th style="min-width:80px" title="Subtotal">Subtotal</th>
        <th style="min-width:80px" title="Desconto">Desconto</th>
        <th style="min-width:80px" title="Total">Total</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @service_orders.each do |service_order| %>
        <tr>
          <td>
            <%= link_to edit_service_order_path(service_order), title: "Editar OS:"+service_order.id.to_s do%><%=service_order.id%><%end%>
          </td>
          <td><%= link_to service_order.customer , :class => "" do %>
              <i class="fa fa-user"> <%= service_order.customer.name %></i>
            <% end %>
          </td>
          <td class="hidden-sm hidden-xs">
            <% if(not service_order.vehicle.nil?) %>
                <%= link_to service_order.vehicle , :class => "" do %>
                  <i class="fa fa-truck">
                    <%=  (format_license_plate(service_order.vehicle.license_plate) << " " <<  service_order.vehicle.description) %></i>

                <% end %>
            <%end%>
          </td>
          <td class="hidden-sm hidden-xs"><%= service_order.created_at.nil? ? '' : l(service_order.created_at, :format => :short_brev) %></td>
          <td class="hidden-sm hidden-xs"><%= service_order.payment_date.nil? ? '' : l(service_order.payment_date, :format => :short_brev) %></td>
          <td><span class="label label-<%= service_order.paid ? 'success' : 'danger' %>"><%= service_order.paid ? 'Sim' : "Não" %></span></td>
          <td class="hidden-sm hidden-xs"> <span class="label label-<%= service_order.os_created ? 'success' : 'danger' %>"><%= service_order.os_created ? 'sim' : 'não' %></span></td>
          <td class="hidden-sm hidden-xs"><span class="label label-<%= service_order.help ? 'success' : 'danger' %>"><%= service_order.help ? 'sim' : 'não' %></span></td>
          <td class="hidden-sm hidden-xs"><%= tipo_pagamento_desc(service_order.payment_type) %></td>
          <% if (policy(ServiceOrder).show_user_column?) %>
            <td><%= service_order.user.nil? ? "" : service_order.user.full_name %></td>
          <% end %>
          <td><%= number_to_currency( service_order.subtotal ) %></td>
          <td><%= service_order.discount > 0 ? "R$ -" << number_to_currency_br( service_order.discount ).to_s.strip : ""%></td>
          <td><%= number_to_currency( service_order.total ) %></td>
          <td>
            <div class="btn-group dropup btn-group-table">
                <!--<button type="button" class="btn btn-success" data-toggle="dropdown">Ações</button>-->
                <button type="button" class="btn btn-success dropdown-toggle" data-toggle="dropdown" title="Ações">
                  <span class="caret"></span>
                  <span class="sr-only">Toggle Dropdown</span>
                </button>
                <ul class="dropdown-menu" role="menu">
                   <li><%= link_to service_order do %><i class="fa fa-eye"> Exibir</i><% end %></li>
                   <li>
                    <%= link_to service_order_path(service_order), method: :delete, data: { confirm: "Você tem certeza?" } do %>
                      <i class="fa fa-trash-o"></i> Remover
                    <% end %>
                   </li>
                   <li><%= link_to edit_service_order_path(service_order) do%><i class="fa fa-edit"> Editar</i><% end %></li>
                   <li>
                    <%= link_to report_service_orders_path(service_order), target: "_blank"  do%><i class="fa fa-print"> Imprimir</i><% end %>
                   </li>
                   <li>
                      <%= link_to service_order_path(service_order, format: :pdf), target: "_blank" do %>
                        <i class="fa fa-file-pdf-o"></i> Versão PDF
                      <% end %>
                   </li>
                   <li>
                     <a data-toggle="modal" href="#sendMailDialog" class="send-mail" so-id="<%= service_order.id %>">
                       <i class="fa fa-mail-forward"></i> Enviar Email
                     </a>
                   </li>
                </ul>
              </div>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <div class="row-fluid" align="center">
    <%= will_paginate @service_orders,next_label: "»",previous_label: "«", renderer: BootstrapPagination::Rails%>
  </div>
  <div class="modal-footer">
    <%= link_to new_service_order_path , :class => "btn btn-primary pull-left" do %>
      <i class="fa fa-file-text"> Novo</i>
    <% end %>
  </div>
</div>

<%= render "send_mail" %>

<%= render 'search_customers' %>
<script type="text/javascript">
  jQuery(document).ready(function ($) {
    ServiceOrdersCustomersJS.initCustomersSearchForm("#customer_id", "#customer_name", "", "", "#vehicle");
    ServiceOrder.buttonStatusTodos();
    $('.input-group.date').datepicker({format:'dd/mm/yyyy',language: "pt-BR",autoclose: true,todayHighlight: true});
  });
</script>

<%= render "remover_os"%>

app/views/service_orders/report.html.erb
<div class="buttonArea">
	<div class="btn-group dropdown">
    <button type="button" class="btn btn-success" data-toggle="dropdown">Ações</button>
    <button type="button" class="btn btn-success dropdown-toggle" data-toggle="dropdown">
      <span class="caret"></span>
    </button>
    <ul class="dropdown-menu" role="menu">
      <li>
        <%= link_to edit_service_order_path(@service_order) do%>
          <i class="fa fa-edit"></i> Editar
        <% end %>
      </li>
      <li>
        <%= link_to service_orders_path do %>
          <i class="fa fa-list-ul"></i> Listar OS
        <% end %>
      </li>
      <li>
        <%= link_to report_service_orders_path(@service_order), target: "_blank"  do%>
          <i class="fa fa-print"></i> Imprimir
        <% end %>
      </li>
      <li>
        <%= link_to service_order_path(@service_order, format: :pdf), target: "_blank" do %>
          <i class="fa fa-file-pdf-o"></i> Versão PDF
        <% end %>
      </li>
    </ul>
  </div>
</div>
<br/>
<div class="row" class="header">
	<div class="col-xs-3" align="right" style="padding-top: 6%">
		<%= image_tag("logo-for-report.jpg") %>
	</div>
	<div class="col-xs-6">

		<div align="center">
			<h3><strong><%= @company.fantasy_name %></strong></h3>
			<br/>
			<p><%= h_address(@company) %></p>
			<p>Tel: <%= @company.phone %> / <%= @company.phone2 %></p>
			<p>E-mail: <%= @company.email %></p>
			<p><%= @company.observation %></p>
		</div>
	</div>
</div>
<hr/>
<br/>
<div align="center">
	<h4>
	    <i>
	      <%= @service_order.payment_type == 9 ? "Orçamento" : "Demonstrativo de serviços prestados" %>
	    </i>
	</h4>
</div>
<br/>
<div class="panel panel-default">
	<div class="panel-body">
		<div class="row">
			<div class="col-xs-12">
				Cliente: <%= @service_order.customer.name %>
			</div>
		</div>
		<% unless (@service_order.vehicle.nil?) %>
			<div class="row">
				<div class="col-xs-6">
					Veículo: <%= @service_order.vehicle.description %>
				</div>
				<div class="col-xs-3">
					Ano: <%= @service_order.vehicle.year_model %>
				</div>
				<div class="col-xs-3">
					Placa: <%= @service_order.vehicle.license_plate %>
				</div>
			</div>
		<% end %>
		<div class="row">
			<div class="col-xs-12">
				Telefone: <%= get_phones(@service_order.customer) %>
			</div>
		</div>
	</div>
</div>
<table class="table-print">
	<thead>
		<tr>
			<th>DATA</th>
			<th>SERVIÇOS PRESTADOS</th>
			<% unless (@service_order.payment_type == 9) %>
				<th>TOTAL</th>
			<% end %>
		</tr>
	</thead>
	<tbody>

		<% total = 0.0 %>

		<% @service_order.service_order_item.each do |soi| %>

			<% total += soi.unit_price || 0 %>

			<tr>
				<td><%= l(soi.soi_date, :format => :default) %></td>
				<td><%= soi.service_order_item_description.nil? ? "" : soi.service_order_item_description.description %></td>
				<% unless (@service_order.payment_type == 9) %>
					<td align="right"><%= number_to_currency(soi.unit_price || 0 ) %></td>
				<% end %>
			</tr>
		<% end %>
	</tbody>
</table>

<% unless (@service_order.observations.blank?)%>
<div class="panel panel-default"  style="margin-top:5px">
  <div class="panel-body" style="padding: 5px 20px 5px 20px;">
    <div class="row">
      <div>
        <strong>Observações:</strong> 
        <br/>
				<%= sanitize @service_order.observations%>
      </div>
    </div>
  </div>
</div>
<% end %>
<% unless (@service_order.payment_type == 9) %>
	<br/>
	<hr/>	
	<div align="right">
		<%if (not @service_order.discount.nil? and @service_order.discount > 0)%>	  
			<h4>Subtotal: R$<span class="formata-total"><%= number_to_currency_br(total) %></span></h4>
		    <h4>Desconto: R$<span class="formata-total">-<%= number_to_currency_br(@service_order.discount) %></span></h4>
		    <br/>	 
		 <%end%>
		<h4>Total:<span class="formata-total"><%= number_to_currency_br(total - @service_order.discount) %></span></h4>
	</div>
<% end %>