config/routes.rb
Rails.application.routes.draw do
  
  root 'home#index' 

  scope(:path_names => { :new => "novo", :edit => "editar" }) do

    #location urls
    get "localizacao/cidades/estado/:state_id" => "location#cities_from_state"
    get "localizacao/estados" => "location#states"

    get "osid/novo" => "service_order_item_description#create" 
    get "osid/descricao" => "service_order_item_description#description_items", :as => "description_items"   

    resources :vehicles, :path => "veiculos", except: :destroy do
      collection do
        get "/:state_id/cities_from_state" => "vehicles#cities_from_state", :as => "cities_from_state", :format => :json
        get "/find" => "vehicles#find", :as => "find"
      end
    end

    resources :customers, :path => "clientes", except: :destroy do
      collection do
        get "/buscarVeiculos" => "customers#search_vehicle", :as => "search_vehicle"        
        get "/find" => "customers#find", :as => "find"
      end
    end

    resources :service_orders, :path => "os" do
      collection do
        get "/descricao" => "service_orders#description_items", :as => "description_items"
        get "/buscar" => "service_orders#find", :as => "buscar"
        get "/:id/emissao" => "service_orders#report", :as => "report"
        post "/enviar/email" => "service_orders#send_mail", :as => "send_mail"
      end
    end

    resources :users, :path => "usuarios", except: :destroy

    resource :company, :path => "empresa", :controller => :company, :only => [:edit, :show, :update, :create]

    devise_for :users, path: "", path_names: { sign_in: 'entrar', sign_out: 'sair', password: 'senha', confirmation: 'confirmacao', unlock: 'desbloqueio', registration: 'registro', sign_up: 'cadastro' }
  end

end

app/models/vehicle.rb
class Vehicle < ActiveRecord::Base
	self.per_page = 10

  	belongs_to :state
  	belongs_to :city
    belongs_to :user

    has_many :customer_vehicle, autosave: true, dependent: :destroy
    has_many :customervehicle, through: :customer_vehicle
    accepts_nested_attributes_for :customer_vehicle, allow_destroy: true
  	# has_and_belongs_to_many :customer

  	before_save :treat_plate, :upper_vehicle

    validates :user_id, presence: :true
    validates :description, presence: :true
    validates :license_plate, presence: :true
    # validates :year_model, presence: :true

  	private
  		def treat_plate
  			self.license_plate = self.license_plate.gsub("-","")
  			self.year_model = self.year_model.gsub("-","")
  		end

      def upper_vehicle
        self.chassi = self.chassi.upcase
        self.license_plate = self.license_plate.upcase
      end
end

app/controllers/vehicles_controller.rb
class VehiclesController < ApplicationController
  
  before_action :authenticate_user!
  before_action :set_vehicle, only: [:show, :edit, :update, :destroy]

  layout "main_application"
  # GET /vehicles
  # GET /vehicles.json
  def index
    @vehicles = Vehicle.all.order("description").paginate(:page => params[:page])
  end

  # GET /vehicle/find
  def find
    @vehicles = Vehicle.where("description LIKE ? AND license_plate LIKE ?", "%#{params[:description]}%", "%#{params[:license_plate]}%".gsub("-","")).order("description").paginate(:page => params[:page])

    respond_to do |format|
        format.html { render :index }
    end
  end

  # GET /vehicles/1
  # GET /vehicles/1.json
  def show
  end

  # GET /vehicles/new
  def new
    @vehicle = Vehicle.new 
    @vehicle.status = '1';
    @cities = []
  end

  # GET /vehicles/1/edit
  def edit
    @vehicle = Vehicle.find(params[:id])
    @cities = []

    if (@vehicle.city)
      @cities = load_cities(@vehicle.city.state_id)
    end
  end

  # POST /vehicles
  # POST /vehicles.json
  def create
    @vehicle = Vehicle.new(vehicle_params)

    @vehicle.user = current_user

    respond_to do |format|
      if @vehicle.save
        format.html { redirect_to @vehicle, notice: 'Veículo criado com sucesso.' }
        format.json { render :show, status: :created, location: @vehicle }
      else
        format.html { render :new }
        format.json { render json: @vehicle.errors, status: :unprocessable_entity }
      end

      @cities = []

      if (@vehicle.city)
        @cities = load_cities(@vehicle.city.state_id)
      end
    end
  end

  # PATCH/PUT /vehicles/1
  # PATCH/PUT /vehicles/1.json
  def update

    @vehicle.user = current_user
    
    respond_to do |format|
      if @vehicle.update(vehicle_params)
        format.html { redirect_to @vehicle, notice: 'Veículo atualizado com sucesso.' }
        format.json { render :show, status: :ok, location: @vehicle }
      else
        format.html { render :edit }
        format.json { render json: @vehicle.errors, status: :unprocessable_entity }
      end

      @cities = []

      if (@vehicle.city)
        @cities = load_cities(@vehicle.city.state_id)
      end
    end
  end

  def cities_from_state
    @cities = load_cities(params[:state_id])

    respond_to do |format|
      format.json { render json: @cities, :status => :created}
    end
  end

  private
    
    def load_cities(stateId)
      City.joins(:state).where("states.id = ? ", stateId)
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_vehicle
      @vehicle = Vehicle.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def vehicle_params
      params.require(:vehicle).permit(:description, :city, :license_plate, :year_model, :chassi, :city_id, :status)
    end

end

app/helpers/vehicles_helper.rb
module VehiclesHelper

	def format_license_plate(license_plate)
		license_plate_formatted = license_plate

		if (license_plate and license_plate.length >= 7)
			license_plate_formatted = license_plate[0,3] +"-"+ license_plate[3,6]
			license_plate_formatted = license_plate_formatted.upcase
		end

		license_plate_formatted
	end

	def format_year_model(year_model)
		year_model_formatted = year_model

		if (year_model and year_model.length >= 8)
			year_model_formatted = year_model[0,4] +"-"+ year_model[4,7]
		end

		year_model_formatted
	end

	def format_status(status)
		if(status and status == '1')
			"Ativo"
		else
			"Inativo"
		end
	end

	def format_status_class(status)
		if(status and status == '1')
			"btn-success"
		else
			"btn-danger"
		end
	end
end

app/views/vehicles/_form.html.erb
<div class="row">
  <div class="col-lg-10">

    <%= form_for(@vehicle, html: {role: "form"}) do |f| %>

      <div class="row">
        <div class="form-group col-lg-6 has-feedback <%= (not @vehicle.errors[:description].empty?) ? "has-error" : "" %>">
            <%= f.label :description, "Descrição", :class => "control-label" %>
            <% if (@vehicle.errors[:description].empty?) %>
              <span class="obrigatorio">*</span>
            <% end %>
            <%= f.text_field :description , :class => "form-control", :placeholder => "Descrição do veículo"%>
            <% if (not @vehicle.errors[:description].empty?) %>
              <span class="fa fa-times form-control-feedback"></span>
            <% end %>
            <p class="help-block">
              <%= @vehicle.errors[:description].first %>
            </p>
        </div>

        <div class="form-group col-lg-6 has-feedback <%= @vehicle.errors[:chassi].count >= 1 ? "has-error" : "" %>">
          <%= f.label :chassi, "Chassi", :class => "control-label" %>
          <%= f.text_field :chassi , :class => "form-control upper", maxlength: 17 %>
          <% if (@vehicle.errors[:chassi].count >= 1) %>
            <span class="fa fa-times form-control-feedback"></span>
          <% end %>
          <p class="help-block">
            <%= @vehicle.errors[:chassi].first %>
          </p>
        </div>
      </div>

      <div class="row">
        <div class="form-group col-lg-6 has-feedback <%= (not @vehicle.errors[:state_id].empty?) ? "has-error" : "" %>">
            <%= label :state, :state_id, "Estados/UF", :class => "control-label" %>
            <%= collection_select :state, :state_id, State.all, :id, :name, {:prompt => "Selecione...", :selected => @vehicle.city ? @vehicle.city.state_id : ""}, {:class => 'form-control'} %>
            <% if (not @vehicle.errors[:state_id].empty?) %>
              <span class="fa fa-times form-control-feedback"></span>
            <% end %>
            <p class="help-block">
              <%= @vehicle.errors[:state_id].first %>
            </p>
        </div>

        <div class="form-group col-lg-6 has-feedback <%= (not @vehicle.errors[:city_id].empty?) ? "has-error" : "" %>">
          <%= f.label :city_id, "Cidades", :class => "control-label" %>
          <%= f.collection_select :city_id, @cities, :id, :name, {:prompt => "Selecione..."}, {:class => 'form-control'} %>
          <% if (not @vehicle.errors[:city_id].empty?) %>
            <span class="fa fa-times form-control-feedback"></span>
          <% end %>
          <p class="help-block">
            <%= @vehicle.errors[:city_id].first %>
          </p>
        </div>
      </div>

      <div class="row">
        <div class="form-group col-lg-6 has-feedback <%= (not @vehicle.errors[:license_plate].empty?) ? "has-error" : "" %>">
            <%= f.label :license_plate, "Placa", :class => "control-label" %>
            <% if (@vehicle.errors[:license_plate].empty?) %>
              <span class="obrigatorio">*</span>
            <% end %>
            <%= f.text_field :license_plate , :class => "form-control license_plate upper"%>
            <% if (not @vehicle.errors[:license_plate].empty?) %>
              <span class="fa fa-times form-control-feedback"></span>
            <% end %>
            <p class="help-block">
              <%= @vehicle.errors[:license_plate].first %>
            </p>
        </div>

        <div class="form-group col-lg-6 has-feedback <%= (not @vehicle.errors[:year_model].empty?) ? "has-error" : "" %>">
            <%= f.label :year_model, "Ano/Modelo", :class => "control-label" %>
            <% if (@vehicle.errors[:year_model].empty?) %>
              <span class="obrigatorio">*</span>
            <% end %>
            <%= f.text_field :year_model , :class => "form-control year_model" %>
            <% if (not @vehicle.errors[:year_model].empty?) %>
              <span class="fa fa-times form-control-feedback"></span>
            <% end %>
            <p class="help-block">
              <%= @vehicle.errors[:year_model].first %>
            </p>
        </div>
      </div>

      <div class="form-group">
          <%= f.label :status, "Status", :class => "control-label" %><br/>
          <%= f.button "tag" , :class => "btn "+format_status_class(@vehicle.status), :id => "btn-status", :type => "button" do %>
            <%=format_status(@vehicle.status) %>
          <% end%>
          <%= f.hidden_field :status%>
      </div>

      <hr>
      <%= f.button :submit, class: "btn btn-primary", data: {disable_with: "<i class='fa fa-spinner fa-spin'></i> Salvando..."} do %>
        <i class="fa fa-save"></i> Salvar
      <% end %>

      <% if(@vehicle.id?) %>
         <%=  link_to @vehicle , :class => "btn btn-success" do %> 
          <i class="fa fa-eye"></i> Exibir
         <% end %>
       <% end %>

      <%= link_to vehicles_path, :class => "btn btn-default" do %>
          <i class="fa fa-list-ul"></i> Listar Veículos
      <% end %>
    <% end %>
  </div>
</div>
<script type="text/javascript">
  $(function() {
    Common.initCombos("#state_state_id","#vehicle_city_id");
    VehiclesJS.initInputMasks();
    $("#vehicle_description").focus();
    Common.buttonStatus("#vehicle_status")
  });
</script>
<%= render 'layouts/loading_modal' %>

app/views/vehicles/edit.html.erb
<div class="row">
  <div class="col-lg-12">
	<h1 class="hidden-sm hidden-xs">Editar Veículo</h1>
	<br class="visible-xs-* visible-md-*" />
	<ol class="breadcrumb">
	  <li><i class="fa fa-home"></i> <%= link_to 'Home', root_path %></li>
  	  <li><i class="fa fa-truck"></i> <%= link_to 'Veículos', vehicles_path %></li>
      <li class="active"><i class="fa fa-pencil-square-o"></i> Editar</li>
	</ol>
	<hr/>
  </div>
</div>
<%= render 'form' %>

app/views/vehicles/index.html.erb
<h1 class="hidden-sm hidden-xs">Lista de Veículos</h1>
<br class="visible-xs-* visible-md-*" />
<ol class="breadcrumb">
  <li><i class="fa fa-home"></i> <%= link_to 'Home', root_path %></li>
  <li class="active"><i class="fa fa-truck"></i> Veículos</li>
</ol>
<hr/>
<div class="panel panel-primary">
    <div class="panel-heading">
        <h3 class="panel-title"><i class="fa fa-search"></i> Buscar</h3>
    </div>
    <div class="panel-body">
        <%= form_tag find_vehicles_path , :method => "get" do%>
          <div class="row">
            <div class="form-group-sm col-lg-2">
              <%= label_tag(:description, "Descrição") %>
              <%= text_field_tag(:description, params[:description], class: "form-control year_model") %>
            </div>
            <div class="form-group-sm col-lg-2">
              <%= label_tag(:license_plate, "Placa") %>
              <%= text_field_tag(:license_plate, params[:license_plate], class: "form-control license_plate") %>
            </div>
            <div class="form-group-sm col-lg-2" style="margin-top: 23px;">
              <%= button_tag :submit, class: "btn btn-primary" do %>
                <i class="fa fa-search"></i> Buscar
              <% end %>              
            </div>
          </div>
        <% end %>
    </div>
</div>

<%= link_to new_vehicle_path , :class => "btn btn-primary" do %>
  <i class="fa fa-truck"> Novo</i>
<% end %>
<br/><br/>
<!--por causa do mobile <div class="table-responsive">-->
  <table class="table table-bordered table-hover table-data">
    <thead>
      <tr>
        <th>Descrição</th>
        <th class="hidden-sm hidden-xs">Placa</th>
        <th class="hidden-sm hidden-xs">Estado</th>
        <th class="hidden-sm hidden-xs">Cidade</th>        
        <th class="hidden-sm hidden-xs">Ano/Modelo</th>
        <th class="hidden-sm hidden-xs">Chassi</th>
        <% if (policy(Vehicle).show_user_column?) %>
          <th>Alterado por</th>
        <% end %>
        <th colspan="3" class="last"></th>
      </tr>
    </thead>

    <tbody>
      <% @vehicles.each do |vehicle| %>
        <tr>
          <td class="<%= vehicle.status == '1' ? 'status-ativo' : 'status-inativo'%>"><%= vehicle.description %></td>
          <td class="hidden-sm hidden-xs"><%= format_license_plate(vehicle.license_plate) %></td>
          <td class="hidden-sm hidden-xs"><%= vehicle.city and vehicle.city.state ? vehicle.city.state.name : ''%></td>
          <td class="hidden-sm hidden-xs"><%= vehicle.city ? vehicle.city.name : '' %></td>          
          <td class="hidden-sm hidden-xs"><%= format_year_model(vehicle.year_model) %></td>
          <td class="hidden-sm hidden-xs"><%= vehicle.chassi %></td>
          <% if (policy(Vehicle).show_user_column?) %>
            <td><%= vehicle.user.nil? ? "" : vehicle.user.full_name %></td>
          <% end %>
          <td class="last"><div class="btn-group dropup btn-group-table">
              <button type="button" class="btn btn-success" data-toggle="dropdown">Ações</button>
              <button type="button" class="btn btn-success dropdown-toggle" data-toggle="dropdown">
                <span class="caret"></span>
                <span class="sr-only">Toggle Dropdown</span>
              </button>
              <ul class="dropdown-menu" role="menu">
                 <li><%= link_to vehicle do %><i class="fa fa-eye"> Exibir</i><% end %></li>
                 <li><%= link_to edit_vehicle_path(vehicle) do%><i class="fa fa-edit"> Editar</i><% end %></li>
              </ul>
            </div>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<!--</div>-->
<div class="row-fluid" align="center">
  <%= will_paginate @vehicles,next_label: "»",previous_label: "«", renderer: BootstrapPagination::Rails%>
</div>
<br>

<%= link_to new_vehicle_path , :class => "btn btn-primary" do %>
<i class="fa fa-truck"> Novo</i>
<% end %>

<script type="text/javascript">
  $(function() {
    VehiclesJS.initInputMasks();
  });
</script>

app/views/vehicles/new.html.erb
<div class="row">
  <div class="col-lg-12">
	<h1 class="hidden-sm hidden-xs">Novo Veículo</h1>
	<br class="visible-xs-* visible-md-*" />
	<ol class="breadcrumb">
      <li><i class="fa fa-home"></i> <%= link_to 'Home', root_path %></li>
      <li><i class="fa fa-truck"></i> <%= link_to 'Veículos', vehicles_path %></li>
      <li class="active"><i class="fa fa-truck"></i> Novo</li>
    </ol>
    <hr/>    
  </div>
</div>
<%= render 'form' %>

app/views/vehicles/show.html.erb
<h1 class="hidden-sm hidden-xs">Visualizar Veículo</h1>
<br class="visible-xs-* visible-md-*" />
<ol class="breadcrumb">
  <li><i class="fa fa-home"></i> <%= link_to 'Home', root_path %></li>
  <li><i class="fa fa-truck"></i> <%= link_to 'Veículos', vehicles_path %></li>
  <li class="active"><i class="fa fa-eye"></i> Visualizar</li>
</ol>
<hr/>
<div class="row">
  <% if (notice) %>
	<div class="alert alert-info alert-dismissable">
		<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
		<i class="fa fa-truck"></i> <%= notice %>
	</div>
  <% end %>
  
  <div class="col-lg-4">
	<!--<form class="form-horizontal" role="form">-->
		<div class="form-group-sm">
			<label class="col-lg-4-sm control-label">Descrição:</label>
		  	<span class="form-control-static"><%= @vehicle.description %></span>
		</div>
		
		<div class="form-group-sm">
		    <label class="col-lg-4-sm control-label">Estado:</label>
		  	<span class="form-control-static"><%= @vehicle.city ? @vehicle.city.state.name : ''%></span>
		</div>
		
		<div class="form-group-sm">
		    <label class="col-lg-4-sm control-label">Cidade:</label>
		  	<span class="form-control-static"><%= @vehicle.city ? @vehicle.city.name : '' %></span>
		</div>
		
		<div class="form-group-sm">
		    <label class="col-lg-4-sm control-label">Placa:</label>
		    <span class="form-control-static"><%= (@vehicle.license_plate ? @vehicle.license_plate[0,3] +"-"+ @vehicle.license_plate[3,6] : '').upcase %></span>
		</div>

		<div class="form-group-sm">
		    <label class="col-lg-4-sm control-label">Ano/Modelo:</label>
		    <span class="form-control-static"><%= @vehicle.year_model ? @vehicle.year_model[0,4] +"-"+ @vehicle.year_model[4,7] : '' %></span>
		</div>
		<div class="form-group-sm">
		    <label class="col-lg-4-sm control-label">Chassi:</label>
		    <span class="form-control-static"><%= @vehicle.chassi%></span>
		</div>
		<div class="form-group-sm">
		    <label class="col-lg-4-sm control-label">Status:</label>
		    <span class="label label-<%=@vehicle.status == '1' ? 'success' : 'danger' %>"><%= format_status(@vehicle.status)%></span>
		</div>
	<!--</form>-->

	</div>
</div>
<hr/>
<%= link_to new_vehicle_path , :class => "btn btn-primary" do %>
<i class="fa fa-truck"> Novo</i>
<% end %>

<%= link_to  edit_vehicle_path(@vehicle), :class => "btn btn-info" do %>
	<i class="fa fa-edit"></i> Editar
<% end %>

<%= link_to vehicles_path, :class => "btn btn-default"  do %>
	<i class="fa fa-list-ul"></i> Listar Veículos
<% end %>