config/routes.rb
Rails.application.routes.draw do
  
  root 'home#index' 

  scope(:path_names => { :new => "novo", :edit => "editar" }) do

    #location urls
    get "localizacao/cidades/estado/:state_id" => "location#cities_from_state"
    get "localizacao/estados" => "location#states"

    get "osid/novo" => "service_order_item_description#create" 
    get "osid/descricao" => "service_order_item_description#description_items", :as => "description_items"   

    resources :vehicles, :path => "veiculos", except: :destroy do
      collection do
        get "/:state_id/cities_from_state" => "vehicles#cities_from_state", :as => "cities_from_state", :format => :json
        get "/find" => "vehicles#find", :as => "find"
      end
    end

    resources :customers, :path => "clientes", except: :destroy do
      collection do
        get "/buscarVeiculos" => "customers#search_vehicle", :as => "search_vehicle"        
        get "/find" => "customers#find", :as => "find"
      end
    end

    resources :service_orders, :path => "os" do
      collection do
        get "/descricao" => "service_orders#description_items", :as => "description_items"
        get "/buscar" => "service_orders#find", :as => "buscar"
        get "/:id/emissao" => "service_orders#report", :as => "report"
        post "/enviar/email" => "service_orders#send_mail", :as => "send_mail"
      end
    end

    resources :users, :path => "usuarios", except: :destroy

    resource :company, :path => "empresa", :controller => :company, :only => [:edit, :show, :update, :create]

    devise_for :users, path: "", path_names: { sign_in: 'entrar', sign_out: 'sair', password: 'senha', confirmation: 'confirmacao', unlock: 'desbloqueio', registration: 'registro', sign_up: 'cadastro' }
  end

end

app/views/layouts/_loading_modal.html.erb
<div id="loading_modal" class="modal bs-example-modal-sm" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel" aria-hidden="true">
	<div class="modal-dialog modal-sm">
	    <div class="modal-content">
		    <div class="modal-header">
		       <!-- <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>-->
		        <h4 class="modal-title" id="myModalLabel">Loading</h4>
	      	</div>
	      	<div class="modal-body">
	        	<h1 class="text-center"><i class="fa fa-spinner fa-spin"></i></h1>
	      	</div>	      
	    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="">
  <meta name="author" content="">
  <%= favicon_link_tag 'favicon.ico' %>
  <title>.:: Mecânica Bálsamo Benz ::.</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
<%= javascript_include_tag Ckeditor.cdn_url %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <style type="text/css">
    #page-wrapper-solo {
      width: 70%;
      margin-left: 15%;
      margin-top: 80px;
    }
  </style>
</head>
<body>

	<div id="wrapper">

      <!-- Sidebar -->
      <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%# link_to "Mecânica", root_path, :class => "navbar-brand" %>
          <img src="<%= asset_path 'logo-interno.png'%>" heigth="95" width="95" style="padding: 5px; margin-left:10px">
        </div>
      </nav>

      <div id="page-wrapper-solo" align="center">

        <%= yield %>

      </div><!-- /#page-wrapper -->

    </div><!-- /#wrapper -->

</body>
</html>

app/views/layouts/main_application.html.erb
<!DOCTYPE html>
<html ng-app="orgmyself">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="">
  <meta name="author" content="">
  <%= favicon_link_tag 'favicon.ico' %>
  <title>.:: Mecânica Bálsamo Benz ::.</title>
 <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>

  <%= javascript_include_tag Ckeditor.cdn_url %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
   <link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.4/themes/smoothness/jquery-ui.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.4/jquery-ui.min.js"></script>

  
</head>
<body>
	<!--
	<div ng-view>
	</div>
	-->
	<div id="wrapper">
   <!-- Sidebar -->
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <% #link_to "Mbb", root_path, :class => "navbar-brand" %>
        <img src="<%= asset_path 'logo-interno.png'%>" heigth="95" width="95" style="padding: 5px; margin-left:10px">
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse navbar-ex1-collapse">
        <ul class="nav navbar-nav side-nav">
          <li class="<%= controller?("home") ? "active" : "" %>">
            <%= link_to root_path do %>
              <i class="fa fa-dashboard"></i> Dashboard
            <% end %>
          </li>
          <li class="<%= controller?("customers") ? "active" : "" %>">
            <%= link_to customers_path do %>
              <i class="fa fa-users"></i> Clientes
            <% end %>
          </li>
          <li class="<%= controller?("vehicles") ? "active" : "" %>">
            <%= link_to vehicles_path do %>
              <i class="fa fa-truck"></i> Veículos
            <% end %>
          </li>
          <% if (policy(User).index?) %>
            <li class="<%= controller?("users") ? "active" : "" %>">
              <%= link_to users_path do %>
                <i class="fa fa-user"></i> Usuários
              <% end %>
            </li>
          <% end %>
          <li class="<%= controller?("service_orders") ? "active" : "" %>">
            <%= link_to service_orders_path do %>
              <i class="fa fa-file-text"></i> Ordens de Serviço
            <% end %>
          </li>
          <% if (policy(Company).index?) %>
            <li class="<%= controller?("company") ? "active" : "" %>">
              <%= link_to company_path do %>
                <i class="fa fa-building-o"></i> Dados da Empresa
              <% end %>
            </li>
          <% end %>
        </ul>
        <% if(current_user) %>
          <ul class="nav navbar-nav navbar-right navbar-user">
            <li class="dropdown user-dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-user"></i>  <%= current_user.full_name %>  <b class="caret"></b></a>
                <ul class="dropdown-menu">
                  <li>
                    <%= link_to user_path(current_user) do %>
                      <i class="fa fa-user"></i> Perfil</a>
                    <% end %>
                  </li>
                  <!--
                  <li><a href="#"><i class="fa fa-envelope"></i> Inbox <span class="badge">7</span></a></li>
                  <li><a href="#"><i class="fa fa-gear"></i> Settings</a></li>
                  -->
                  <li class="divider"></li>
                  <li>
                    <%= link_to(destroy_user_session_path, :method => :delete) do %>
                      <i class="fa fa-power-off"></i> Sair
                    <% end %>
                  </li>
                </ul>
              </li>
            
          </ul>
        <% end %>
      </div><!-- /.navbar-collapse -->
    </nav>

    <div id="page-wrapper">
        
        <%= yield %>

    </div><!-- /#page-wrapper -->

  </div><!-- /#wrapper -->
</body>
</html>

app/views/layouts/report_application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="">
  <meta name="author" content="">
  <%= favicon_link_tag 'favicon.ico' %>
  <title>.:: Mecânica Bálsamo Benz ::.</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body onload="window.print();">

	<div id="wrapper-print">

      <!-- Sidebar -->
      <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%# link_to "Mecânica", root_path, :class => "navbar-brand" %>
          <img src="<%= asset_path 'logo-interno.png'%>" heigth="95" width="95" style="padding: 5px; margin-left:10px">
        </div>
      </nav>

      <div id="page-wrapper-print">

        <%= yield %>

      </div><!-- /#page-wrapper -->

    </div><!-- /#wrapper -->

</body>
</html>